openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /sum:
    get:
      summary: Add two numbers
      parameters:
        - name: a
          in: query
          required: true
          schema:
            type: integer
        - name: b
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: integer
