openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
servers:
- url: /
paths:
  /sum:
    get:
      parameters:
      - explode: true
        in: query
        name: a
        required: true
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: b
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: integer
          description: Successful operation
      summary: Add two numbers
components:
  schemas: {}
